name: 爬蟲測試

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'  # 每 10 分鐘自動執行一次

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: 檢查網路連線
        run: |
          curl -I https://119.hcfd.gov.tw/DTS/caselist/html
